name: Downstream

on: [push, pull_request]

permissions: "read-all"

jobs:
  integration:
    strategy:
      fail-fast: false
      matrix:
        downstream: [botocore, requests]
    runs-on: ubuntu-18.04
    timeout-minutes: 30

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c"

      - name: "Setup Python"
        uses: "actions/setup-python@5ccb29d8773c3f3f653e1705f474dfaa8a06a912"
        with:
          python-version: "3.x"

      - name: "Install dependencies"
        run: python -m pip install --upgrade nox

      - name: "Run downstream tests"
        run: nox -s downstream_${{ matrix.downstream }}
