name: lint

on: [push, pull_request]

permissions: "read-all"

jobs:
  lint:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: "Setup Python"
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: "3.x"
          cache: pip

      - name: "Run pre-commit"
        uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 # v3.0.0

      - name: "Install dependencies"
        run: python -m pip install nox

      - name: "Run mypy"
        run: nox -s mypy
