name: lint

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: "read"

jobs:
  lint:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: "Setup Python"
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: "3.x"
          cache: pip

      - name: "Run pre-commit"
        uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 # v3.0.0

      - name: "Install dependencies"
        run: python -m pip install nox

      - name: "Run mypy"
        run: nox -s mypy
