name: "Scorecard"
on:
  branch_protection_rule:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches: ["main", "1.26.x"]

permissions: read-all

jobs:
  analysis:
    name: "Scorecard"
    runs-on: "ubuntu-latest"
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read
    
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b"
        with:
          persist-credentials: false

      - name: "Run Scorecard"
        uses: "ossf/scorecard-action@ce330fde6b1a5c9c75b417e7efc510b822a35564"
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.SCORECARD_TOKEN }}
          publish_results: true
